// all-in-motion — motion helpers for the web. Plain TypeScript, no dependencies.
// Strip the types for a JS project. The `springPresets` block is generated by
// scripts/spring.py --tokens; everything below it is hand-written.
//
// What is here:
//   springPresets           the twenty spring presets as data (physics + CSS linear())
//   resolve / waapi / motionTransition / reactSpring / springEase
//                           the same preset for WAAPI, Motion (framer-motion), react-spring, GSAP
//   prefersReducedMotion    media-query check
//   readToken / bezier      read CSS custom properties, sample a cubic-bezier in JS
//   blurRadius              blur budget (full on high-refresh, half at 60 Hz, none under reduced motion)
//   transitions             keyframe sets: element, unfoldIn/Out, side, digitIn/Out
//   reveal / playReveal     the exact popover fold (one progress value drives every channel)
//   rollDigits              rolling number: only the changed characters move
//   pressBounce             grow 15 % on `bounce`, settle back on `release`
//   edgeFade                fade only the scroller edge that has more content behind it
//   wheelItem               layout of one item in an endless wheel picker
//   VelocityTracker         gesture velocity for momentum dismissal / snap points
//   damp                    rubber-band resistance past a boundary

export const springPresets = {
  "hover": {
    "use": "every hover change on buttons, links, cards, rows",
    "spring": {
      "response": 0.4,
      "dampingFraction": 0.85,
      "stiffness": 246.74,
      "damping": 26.704,
      "mass": 1,
      "bounce": 0.15,
      "settleSeconds": 0.558,
      "overshoot": 0.0063,
      "cssLinear": "linear(0, 0.0212, 0.0749, 0.1488, 0.2337, 0.3228, 0.4113, 0.4957, 0.574, 0.645, 0.7081, 0.7632, 0.8106, 0.8508, 0.8845, 0.9123, 0.935, 0.9532, 0.9676, 0.9789, 0.9874, 0.9938, 0.9985, 1.0018, 1.004, 1.0053, 1.006, 1.0063, 1.0062, 1.0059, 1.0055, 1.0049, 1.0044, 1.0038, 1.0033, 1.0028, 1.0023, 1.0019, 1.0016, 1.0013, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.14
      }
    }
  },
  "hoverQuick": {
    "use": "instant hover on small icons; a button's pressed colour",
    "ease": {
      "curve": "easeOut",
      "cubicBezier": [
        0.0,
        0.0,
        0.58,
        1.0
      ],
      "seconds": 0.1
    },
    "reducedMotion": "unchanged"
  },
  "hoverScale": {
    "use": "grow on hover: a badge or pill that is a button",
    "spring": {
      "response": 0.36,
      "dampingFraction": 0.9,
      "stiffness": 304.617,
      "damping": 31.416,
      "mass": 1,
      "bounce": 0.1,
      "settleSeconds": 0.48,
      "overshoot": 0.0015,
      "cssLinear": "linear(0, 0.0193, 0.0683, 0.1358, 0.2136, 0.2956, 0.3775, 0.4563, 0.5302, 0.598, 0.6591, 0.7134, 0.7611, 0.8026, 0.8382, 0.8685, 0.8941, 0.9155, 0.9332, 0.9478, 0.9598, 0.9694, 0.9771, 0.9833, 0.9881, 0.9918, 0.9947, 0.9968, 0.9984, 0.9996, 1.0004, 1.0009, 1.0013, 1.0014, 1.0015, 1.0015, 1.0015, 1.0014, 1.0012, 1.0011, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.12
      }
    }
  },
  "cardHover": {
    "use": "small lift or scale of a card under the pointer",
    "spring": {
      "response": 0.24,
      "dampingFraction": 0.8,
      "stiffness": 685.389,
      "damping": 41.888,
      "mass": 1,
      "bounce": 0.2,
      "settleSeconds": 0.324,
      "overshoot": 0.0152,
      "cssLinear": "linear(0, 0.0201, 0.0716, 0.1436, 0.2274, 0.3164, 0.4058, 0.492, 0.5728, 0.6465, 0.7125, 0.7704, 0.8203, 0.8627, 0.8982, 0.9273, 0.9508, 0.9694, 0.9838, 0.9947, 1.0026, 1.0082, 1.0118, 1.014, 1.015, 1.0151, 1.0147, 1.0138, 1.0126, 1.0113, 1.0099, 1.0086, 1.0073, 1.0061, 1.005, 1.0041, 1.0032, 1.0025, 1.0019, 1.0014, 1)"
    },
    "reducedMotion": "unchanged"
  },
  "state": {
    "use": "the default: toggles, selection, filters, list changes, content swaps",
    "spring": {
      "response": 0.27,
      "dampingFraction": 1.0,
      "stiffness": 541.542,
      "damping": 46.542,
      "mass": 1,
      "bounce": 0.0,
      "settleSeconds": 0.397,
      "overshoot": 0.0,
      "cssLinear": "linear(0, 0.0229, 0.0789, 0.1533, 0.2363, 0.321, 0.4033, 0.4805, 0.5512, 0.6149, 0.6714, 0.7209, 0.764, 0.8012, 0.8331, 0.8603, 0.8834, 0.9029, 0.9193, 0.9331, 0.9446, 0.9542, 0.9622, 0.9689, 0.9744, 0.979, 0.9827, 0.9858, 0.9884, 0.9905, 0.9922, 0.9937, 0.9948, 0.9958, 0.9966, 0.9972, 0.9977, 0.9981, 0.9985, 0.9988, 1)"
    },
    "reducedMotion": "unchanged"
  },
  "segmented": {
    "use": "segmented controls, chips, option tiles, pickers",
    "spring": {
      "response": 0.22,
      "dampingFraction": 0.9,
      "stiffness": 815.67,
      "damping": 51.408,
      "mass": 1,
      "bounce": 0.1,
      "settleSeconds": 0.294,
      "overshoot": 0.0015,
      "cssLinear": "linear(0, 0.0194, 0.0686, 0.1364, 0.2144, 0.2965, 0.3786, 0.4575, 0.5315, 0.5993, 0.6604, 0.7147, 0.7624, 0.8037, 0.8392, 0.8694, 0.8949, 0.9162, 0.9339, 0.9484, 0.9602, 0.9698, 0.9775, 0.9835, 0.9883, 0.992, 0.9948, 0.9969, 0.9985, 0.9996, 1.0004, 1.001, 1.0013, 1.0015, 1.0015, 1.0015, 1.0014, 1.0014, 1.0012, 1.0011, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.16
      }
    }
  },
  "emphasis": {
    "use": "important toggles, favourites, snapping onto a choice",
    "spring": {
      "response": 0.28,
      "dampingFraction": 0.72,
      "stiffness": 503.551,
      "damping": 32.314,
      "mass": 1,
      "bounce": 0.28,
      "settleSeconds": 0.45,
      "overshoot": 0.0384,
      "cssLinear": "linear(0, 0.0282, 0.0994, 0.1968, 0.3072, 0.4208, 0.5305, 0.6318, 0.7217, 0.7991, 0.8635, 0.9156, 0.9562, 0.9869, 1.0088, 1.0236, 1.0327, 1.0372, 1.0384, 1.0372, 1.0344, 1.0306, 1.0263, 1.022, 1.0178, 1.0139, 1.0105, 1.0075, 1.0051, 1.0031, 1.0016, 1.0004, 0.9996, 0.9991, 0.9987, 0.9986, 0.9985, 0.9986, 0.9987, 0.9988, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.2
      }
    }
  },
  "bounce": {
    "use": "playful success: an icon or button that confirms a click",
    "spring": {
      "response": 0.18,
      "dampingFraction": 0.56,
      "stiffness": 1218.47,
      "damping": 39.095,
      "mass": 1,
      "bounce": 0.44,
      "settleSeconds": 0.36,
      "overshoot": 0.1196,
      "cssLinear": "linear(0, 0.0437, 0.1533, 0.3003, 0.4614, 0.6192, 0.7616, 0.8814, 0.9755, 1.0437, 1.0881, 1.112, 1.1196, 1.1151, 1.1024, 1.085, 1.0658, 1.0468, 1.0296, 1.0151, 1.0036, 0.9952, 0.9898, 0.9867, 0.9857, 0.9862, 0.9876, 0.9897, 0.992, 0.9942, 0.9963, 0.9981, 0.9995, 1.0005, 1.0012, 1.0016, 1.0017, 1.0017, 1.0015, 1.0013, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.2
      }
    }
  },
  "press": {
    "use": "pointer down on a control (follows the input)",
    "spring": {
      "response": 0.14,
      "dampingFraction": 0.82,
      "stiffness": 2014.205,
      "damping": 73.603,
      "mass": 1,
      "bounce": 0.18,
      "settleSeconds": 0.193,
      "overshoot": 0.0111,
      "cssLinear": "linear(0, 0.0208, 0.0739, 0.1475, 0.2327, 0.3225, 0.4122, 0.4981, 0.5781, 0.6508, 0.7155, 0.772, 0.8206, 0.8617, 0.896, 0.9241, 0.9468, 0.9648, 0.9788, 0.9894, 0.9973, 1.003, 1.0068, 1.0092, 1.0105, 1.0111, 1.011, 1.0105, 1.0098, 1.0089, 1.0079, 1.0069, 1.0059, 1.005, 1.0041, 1.0034, 1.0027, 1.0022, 1.0017, 1.0013, 1)"
    },
    "reducedMotion": "unchanged"
  },
  "release": {
    "use": "pointer up, the control springing back",
    "spring": {
      "response": 0.24,
      "dampingFraction": 0.74,
      "stiffness": 685.389,
      "damping": 38.746,
      "mass": 1,
      "bounce": 0.26,
      "settleSeconds": 0.302,
      "overshoot": 0.0315,
      "cssLinear": "linear(0, 0.0177, 0.0641, 0.1303, 0.2091, 0.2946, 0.3822, 0.4685, 0.5508, 0.6274, 0.6972, 0.7595, 0.8141, 0.8611, 0.9009, 0.934, 0.9609, 0.9823, 0.9988, 1.0112, 1.0201, 1.0261, 1.0296, 1.0313, 1.0315, 1.0305, 1.0288, 1.0266, 1.024, 1.0212, 1.0185, 1.0158, 1.0133, 1.0109, 1.0088, 1.0069, 1.0053, 1.0039, 1.0027, 1.0017, 1)"
    },
    "reducedMotion": "unchanged"
  },
  "drag": {
    "use": "dragged element following the pointer",
    "spring": {
      "response": 0.1,
      "dampingFraction": 0.9,
      "stiffness": 3947.842,
      "damping": 113.097,
      "mass": 1,
      "bounce": 0.1,
      "settleSeconds": 0.134,
      "overshoot": 0.0015,
      "cssLinear": "linear(0, 0.0195, 0.0689, 0.137, 0.2152, 0.2977, 0.3799, 0.459, 0.533, 0.6009, 0.662, 0.7162, 0.7638, 0.805, 0.8404, 0.8705, 0.8959, 0.9171, 0.9347, 0.9491, 0.9608, 0.9703, 0.9779, 0.9839, 0.9886, 0.9922, 0.995, 0.9971, 0.9986, 0.9997, 1.0005, 1.001, 1.0013, 1.0015, 1.0015, 1.0015, 1.0014, 1.0013, 1.0012, 1.0011, 1)"
    },
    "reducedMotion": "unchanged"
  },
  "pressSnap": {
    "use": "two-phase press, phase 1: snap on pointer down",
    "spring": {
      "response": 0.18,
      "dampingFraction": 0.62,
      "stiffness": 1218.47,
      "damping": 43.284,
      "mass": 1,
      "bounce": 0.38,
      "settleSeconds": 0.294,
      "overshoot": 0.0835,
      "cssLinear": "linear(0, 0.0295, 0.1054, 0.2108, 0.3317, 0.4572, 0.5788, 0.691, 0.7899, 0.8737, 0.9417, 0.9944, 1.0331, 1.0594, 1.0752, 1.0825, 1.0831, 1.079, 1.0715, 1.062, 1.0517, 1.0413, 1.0314, 1.0224, 1.0146, 1.0082, 1.003, 0.9991, 0.9963, 0.9944, 0.9934, 0.993, 0.9932, 0.9936, 0.9943, 0.9952, 0.996, 0.9969, 0.9977, 0.9984, 1)"
    },
    "reducedMotion": "unchanged"
  },
  "pressSettle": {
    "use": "two-phase press, phase 2: settle on pointer up",
    "spring": {
      "response": 0.24,
      "dampingFraction": 0.78,
      "stiffness": 685.389,
      "damping": 40.841,
      "mass": 1,
      "bounce": 0.22,
      "settleSeconds": 0.317,
      "overshoot": 0.0199,
      "cssLinear": "linear(0, 0.0193, 0.0692, 0.1394, 0.2218, 0.3098, 0.3989, 0.4853, 0.5667, 0.6415, 0.7087, 0.768, 0.8194, 0.8632, 0.8999, 0.9302, 0.9546, 0.9739, 0.9889, 1.0001, 1.0082, 1.0138, 1.0173, 1.0192, 1.0199, 1.0197, 1.0188, 1.0174, 1.0158, 1.0141, 1.0123, 1.0106, 1.0089, 1.0074, 1.0061, 1.0048, 1.0038, 1.0029, 1.0021, 1.0015, 1)"
    },
    "reducedMotion": "unchanged"
  },
  "surfacePress": {
    "use": "a large surface (hero card, tile) growing under a held press",
    "spring": {
      "response": 0.24,
      "dampingFraction": 0.82,
      "stiffness": 685.389,
      "damping": 42.935,
      "mass": 1,
      "bounce": 0.18,
      "settleSeconds": 0.33,
      "overshoot": 0.0111,
      "cssLinear": "linear(0, 0.0207, 0.0736, 0.1469, 0.2318, 0.3214, 0.4108, 0.4966, 0.5765, 0.6492, 0.7139, 0.7705, 0.8192, 0.8604, 0.8948, 0.9231, 0.9459, 0.9641, 0.9782, 0.989, 0.997, 1.0027, 1.0066, 1.0091, 1.0105, 1.0111, 1.011, 1.0106, 1.0098, 1.0089, 1.0079, 1.0069, 1.006, 1.0051, 1.0042, 1.0035, 1.0028, 1.0022, 1.0017, 1.0013, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.16
      }
    }
  },
  "surfaceRelease": {
    "use": "the same surface relaxing back",
    "spring": {
      "response": 0.34,
      "dampingFraction": 0.68,
      "stiffness": 341.509,
      "damping": 25.133,
      "mass": 1,
      "bounce": 0.32,
      "settleSeconds": 0.561,
      "overshoot": 0.0543,
      "cssLinear": "linear(0, 0.0298, 0.1054, 0.2089, 0.3261, 0.4465, 0.5623, 0.6683, 0.7615, 0.8405, 0.9049, 0.9556, 0.9937, 1.0209, 1.0388, 1.0492, 1.0537, 1.0539, 1.051, 1.0461, 1.04, 1.0335, 1.027, 1.021, 1.0155, 1.0108, 1.0069, 1.0038, 1.0014, 0.9996, 0.9984, 0.9976, 0.9972, 0.9971, 0.9971, 0.9973, 0.9976, 0.998, 0.9983, 0.9987, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.18
      }
    }
  },
  "open": {
    "use": "anything opening or entering: modal, popover, dropdown, toast, drawer",
    "spring": {
      "response": 0.47,
      "dampingFraction": 0.76,
      "stiffness": 178.716,
      "damping": 20.32,
      "mass": 1,
      "bounce": 0.24,
      "settleSeconds": 0.606,
      "overshoot": 0.0254,
      "cssLinear": "linear(0, 0.0185, 0.0666, 0.1348, 0.2154, 0.3023, 0.3906, 0.477, 0.559, 0.6347, 0.7032, 0.764, 0.817, 0.8624, 0.9006, 0.9322, 0.9578, 0.9781, 0.9938, 1.0055, 1.014, 1.0197, 1.0232, 1.025, 1.0254, 1.0248, 1.0235, 1.0217, 1.0196, 1.0174, 1.0152, 1.013, 1.0109, 1.009, 1.0073, 1.0058, 1.0045, 1.0034, 1.0024, 1.0016, 1)"
    },
    "reducedMotion": {
      "spring": {
        "response": 0.3,
        "dampingFraction": 1.0,
        "stiffness": 438.649,
        "damping": 41.888,
        "mass": 1,
        "bounce": 0.0,
        "settleSeconds": 0.441,
        "overshoot": 0.0,
        "cssLinear": "linear(0, 0.0229, 0.0789, 0.1533, 0.2362, 0.3209, 0.4031, 0.4803, 0.5511, 0.6147, 0.6712, 0.7208, 0.7639, 0.8011, 0.833, 0.8602, 0.8833, 0.9028, 0.9192, 0.933, 0.9445, 0.9542, 0.9622, 0.9688, 0.9744, 0.9789, 0.9827, 0.9858, 0.9884, 0.9905, 0.9922, 0.9936, 0.9948, 0.9958, 0.9966, 0.9972, 0.9977, 0.9981, 0.9985, 0.9988, 1)"
      }
    }
  },
  "close": {
    "use": "anything closing: the same surfaces leave without bounce",
    "spring": {
      "response": 0.54,
      "dampingFraction": 0.9,
      "stiffness": 135.386,
      "damping": 20.944,
      "mass": 1,
      "bounce": 0.1,
      "settleSeconds": 0.72,
      "overshoot": 0.0015,
      "cssLinear": "linear(0, 0.0193, 0.0683, 0.1358, 0.2136, 0.2956, 0.3775, 0.4563, 0.5302, 0.598, 0.6591, 0.7134, 0.7611, 0.8026, 0.8382, 0.8685, 0.8941, 0.9155, 0.9332, 0.9478, 0.9598, 0.9694, 0.9771, 0.9833, 0.9881, 0.9918, 0.9947, 0.9968, 0.9984, 0.9996, 1.0004, 1.0009, 1.0013, 1.0014, 1.0015, 1.0015, 1.0015, 1.0014, 1.0012, 1.0011, 1)"
    },
    "reducedMotion": {
      "spring": {
        "response": 0.3,
        "dampingFraction": 1.0,
        "stiffness": 438.649,
        "damping": 41.888,
        "mass": 1,
        "bounce": 0.0,
        "settleSeconds": 0.441,
        "overshoot": 0.0,
        "cssLinear": "linear(0, 0.0229, 0.0789, 0.1533, 0.2362, 0.3209, 0.4031, 0.4803, 0.5511, 0.6147, 0.6712, 0.7208, 0.7639, 0.8011, 0.833, 0.8602, 0.8833, 0.9028, 0.9192, 0.933, 0.9445, 0.9542, 0.9622, 0.9688, 0.9744, 0.9789, 0.9827, 0.9858, 0.9884, 0.9905, 0.9922, 0.9936, 0.9948, 0.9958, 0.9966, 0.9972, 0.9977, 0.9981, 0.9985, 0.9988, 1)"
      }
    }
  },
  "morph": {
    "use": "a control changing width or shape in place (search expanding)",
    "spring": {
      "response": 0.42,
      "dampingFraction": 0.9,
      "stiffness": 223.801,
      "damping": 26.928,
      "mass": 1,
      "bounce": 0.1,
      "settleSeconds": 0.56,
      "overshoot": 0.0015,
      "cssLinear": "linear(0, 0.0193, 0.0683, 0.1358, 0.2136, 0.2956, 0.3775, 0.4563, 0.5302, 0.598, 0.6591, 0.7134, 0.7611, 0.8026, 0.8382, 0.8685, 0.8941, 0.9155, 0.9332, 0.9478, 0.9598, 0.9694, 0.9771, 0.9833, 0.9881, 0.9918, 0.9947, 0.9968, 0.9984, 0.9996, 1.0004, 1.0009, 1.0013, 1.0014, 1.0015, 1.0015, 1.0015, 1.0014, 1.0012, 1.0011, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.18
      }
    }
  },
  "panelSlide": {
    "use": "a sidebar or inner panel sliding",
    "spring": {
      "response": 0.32,
      "dampingFraction": 0.9,
      "stiffness": 385.531,
      "damping": 35.343,
      "mass": 1,
      "bounce": 0.1,
      "settleSeconds": 0.427,
      "overshoot": 0.0015,
      "cssLinear": "linear(0, 0.0194, 0.0684, 0.136, 0.2139, 0.2959, 0.3779, 0.4567, 0.5306, 0.5984, 0.6595, 0.7139, 0.7616, 0.803, 0.8385, 0.8688, 0.8943, 0.9157, 0.9334, 0.948, 0.9599, 0.9695, 0.9772, 0.9834, 0.9882, 0.9919, 0.9947, 0.9969, 0.9985, 0.9996, 1.0004, 1.0009, 1.0013, 1.0014, 1.0015, 1.0015, 1.0015, 1.0014, 1.0012, 1.0011, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.18
      }
    }
  },
  "tabSelect": {
    "use": "a tab or segment indicator sliding under the choice",
    "spring": {
      "response": 0.34,
      "dampingFraction": 0.82,
      "stiffness": 341.509,
      "damping": 30.307,
      "mass": 1,
      "bounce": 0.18,
      "settleSeconds": 0.467,
      "overshoot": 0.0111,
      "cssLinear": "linear(0, 0.0207, 0.0734, 0.1467, 0.2314, 0.3209, 0.4102, 0.496, 0.5759, 0.6485, 0.7132, 0.7699, 0.8186, 0.8599, 0.8944, 0.9227, 0.9456, 0.9638, 0.978, 0.9888, 0.9968, 1.0026, 1.0065, 1.0091, 1.0105, 1.011, 1.011, 1.0106, 1.0099, 1.009, 1.008, 1.007, 1.006, 1.0051, 1.0042, 1.0035, 1.0028, 1.0022, 1.0017, 1.0013, 1)"
    },
    "reducedMotion": {
      "ease": {
        "curve": "easeOut",
        "cubicBezier": [
          0.0,
          0.0,
          0.58,
          1.0
        ],
        "seconds": 0.16
      }
    }
  }
} as const;

export type SpringPreset = keyof typeof springPresets;

type Spring = { response: number; dampingFraction: number; stiffness: number; damping: number; mass: number; settleSeconds: number; cssLinear: string };
type Ease = { curve: string; cubicBezier: number[]; seconds: number };
type Resolved = { spring: Spring } | { ease: Ease };

export function prefersReducedMotion(): boolean {
  return typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches;
}

export function resolve(name: SpringPreset, reduced = prefersReducedMotion()): Resolved {
  const entry = springPresets[name] as unknown as { spring?: Spring; ease?: Ease; reducedMotion: "unchanged" | Resolved };
  if (reduced && entry.reducedMotion !== "unchanged") return entry.reducedMotion;
  return entry.spring ? { spring: entry.spring } : { ease: entry.ease as Ease };
}

/** Web Animations API: `el.animate(frames, waapi("open"))`. */
export function waapi(name: SpringPreset, reduced?: boolean): { duration: number; easing: string; fill: "both" } {
  const r = resolve(name, reduced);
  if ("spring" in r) return { duration: Math.round(r.spring.settleSeconds * 1000), easing: r.spring.cssLinear, fill: "both" };
  return { duration: Math.round(r.ease.seconds * 1000), easing: `cubic-bezier(${r.ease.cubicBezier.join(",")})`, fill: "both" };
}

/** Motion (framer-motion): `<motion.div transition={motionTransition("hover")} />`. */
export function motionTransition(name: SpringPreset, reduced?: boolean) {
  const r = resolve(name, reduced);
  if ("spring" in r) return { type: "spring" as const, stiffness: r.spring.stiffness, damping: r.spring.damping, mass: 1 };
  return { type: "tween" as const, duration: r.ease.seconds, ease: r.ease.cubicBezier };
}

/** react-spring: `useSpring({ ..., config: reactSpring("state") })`. */
export function reactSpring(name: SpringPreset, reduced?: boolean) {
  const r = resolve(name, reduced);
  if ("spring" in r) return { tension: r.spring.stiffness, friction: r.spring.damping, mass: 1 };
  return { duration: r.ease.seconds * 1000 };
}

/** A spring as an easing function over its settle time, for GSAP or a hand-rolled loop. */
export function springEase(response: number, dampingFraction: number): (t: number) => number {
  const omega = (2 * Math.PI) / response;
  const zeta = dampingFraction;
  const x = (t: number) => {
    if (zeta < 1) {
      const wd = omega * Math.sqrt(1 - zeta * zeta);
      return 1 - Math.exp(-zeta * omega * t) * (Math.cos(wd * t) + ((zeta * omega) / wd) * Math.sin(wd * t));
    }
    return 1 - Math.exp(-omega * t) * (1 + omega * t);
  };
  let settle = 0;
  for (let t = 0.001; t < 10 * response + 2; t += 0.001) if (Math.abs(1 - x(t)) > 0.001) settle = t;
  return (p: number) => (p >= 1 ? 1 : x(p * (settle + 0.001)));
}

/** Read a numeric CSS custom property off :root ("px" / "ms" / "s" suffixes ok). */
export function readToken(name: string, fallback: number): number {
  const raw = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  if (!raw) return fallback;
  if (raw.endsWith("ms")) return parseFloat(raw);
  if (raw.endsWith("s")) return parseFloat(raw) * 1000;
  const n = parseFloat(raw);
  return Number.isNaN(n) ? fallback : n;
}

/** Sample a CSS easing (keyword or cubic-bezier(...)) in JS so rAF-driven motion matches CSS. */
export function bezier(raw: string): (t: number) => number {
  const kw: Record<string, number[]> = {
    linear: [0, 0, 1, 1], ease: [0.25, 0.1, 0.25, 1], "ease-in": [0.42, 0, 1, 1],
    "ease-out": [0, 0, 0.58, 1], "ease-in-out": [0.42, 0, 0.58, 1],
  };
  let c = kw[(raw || "").trim()];
  if (!c) {
    const m = (raw || "").match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/);
    if (m) c = [+m[1], +m[2], +m[3], +m[4]];
  }
  if (!c) c = kw.ease;
  const [x1, y1, x2, y2] = c;
  const cx = 3 * x1, bx = 3 * (x2 - x1) - cx, ax = 1 - cx - bx;
  const cy = 3 * y1, by = 3 * (y2 - y1) - cy, ay = 1 - cy - by;
  const sx = (t: number) => ((ax * t + bx) * t + cx) * t;
  const dx = (t: number) => (3 * ax * t + 2 * bx) * t + cx;
  const sy = (t: number) => ((ay * t + by) * t + cy) * t;
  return (x: number) => {
    if (x <= 0) return 0;
    if (x >= 1) return 1;
    let t = x;
    for (let i = 0; i < 8; i++) {
      const e = sx(t) - x;
      if (Math.abs(e) < 1e-5) break;
      const d = dx(t);
      if (Math.abs(d) < 1e-6) break;
      t -= e / d;
    }
    return sy(t);
  };
}

/** Blur budget: full on high refresh, half at 60 Hz, a third in low power, none with reduced motion. */
export function blurRadius(base: number, opts: { hz?: number; lowPower?: boolean; reduced?: boolean } = {}): number {
  if (opts.reduced ?? prefersReducedMotion()) return 0;
  if (opts.lowPower) return Math.max(1, base * 0.33);
  if ((opts.hz ?? 60) <= 60) return Math.max(1.5, base * 0.5);
  return base;
}

/** Transitions as keyframes: `el.animate(transitions.element(), waapi("open"))`. */
export const transitions = {
  element: (blur = blurRadius(14)) => [
    { opacity: 0, filter: `blur(${blur}px)`, transform: "perspective(600px) rotateX(-12deg) scaleX(0.8)", transformOrigin: "50% 0" },
    { opacity: 1, filter: "blur(0px)", transform: "perspective(600px) rotateX(0deg) scaleX(1)", transformOrigin: "50% 0" },
  ],
  unfoldIn: (blur = blurRadius(12)) => [
    { opacity: 0, filter: `blur(${blur}px)`, transform: "perspective(600px) rotateX(-12deg)", transformOrigin: "50% 0" },
    { opacity: 1, filter: "blur(0px)", transform: "perspective(600px) rotateX(0deg)", transformOrigin: "50% 0" },
  ],
  unfoldOut: (blur = blurRadius(12)) => [
    { opacity: 1, filter: "blur(0px)" },
    { opacity: 0, filter: `blur(${blur}px)` },
  ],
  side: (edge: "left" | "right", blur = blurRadius(10)) => [
    { opacity: 0, filter: `blur(${blur}px)`, transform: "scaleX(0)", transformOrigin: edge === "left" ? "0 50%" : "100% 50%" },
    { opacity: 1, filter: "blur(0px)", transform: "scaleX(1)", transformOrigin: edge === "left" ? "0 50%" : "100% 50%" },
  ],
  digitIn: [{ opacity: 0, filter: "blur(3px)", transform: "translateY(7px)" }, { opacity: 1, filter: "blur(0px)", transform: "translateY(0)" }],
  digitOut: [{ opacity: 1, filter: "blur(0px)", transform: "translateY(0)" }, { opacity: 0, filter: "blur(3px)", transform: "translateY(-7px)" }],
};

/** The exact reveal of a popover or card for one progress value p (0 hidden, 1 shown; may overshoot). */
export function reveal(p: number, maxBlur = blurRadius(9), maxFoldDeg = -6) {
  const raw = Number.isFinite(p) ? Math.max(p, 0) : 0;
  const c = Math.min(raw, 1);
  const scaleX = 0.4 + 0.6 * raw;
  const scaleY = 0.2 + 0.8 * raw;
  const rawWash = Math.max(0, 1 - c / 0.97);
  const wash = Math.max(0, (rawWash - 0.12) / 0.88);
  const blur = wash <= 0 ? 0 : (maxBlur * wash * 2.5) / (wash * 1.5 + 1);
  return {
    opacity: Math.pow(c, 1.45),
    filter: `blur(${blur * Math.min(scaleX, scaleY)}px)`,
    transform: `perspective(500px) rotateX(${maxFoldDeg * Math.pow(1 - c, 1.6)}deg) scale(${scaleX}, ${scaleY})`,
    transformOrigin: "50% 0",
  };
}

/** Plays `reveal` on the open spring (or close, reversed) and resolves when it lands. */
export function playReveal(el: HTMLElement, direction: "in" | "out" = "in"): Promise<void> {
  const preset = direction === "in" ? "open" : "close";
  const r = resolve(preset as SpringPreset);
  const spring = "spring" in r ? r.spring : ({ response: 0.3, dampingFraction: 1, settleSeconds: 0.44 } as Spring);
  const ease = springEase(spring.response, spring.dampingFraction);
  const duration = spring.settleSeconds * 1000;
  const start = performance.now();
  return new Promise((done) => {
    const frame = (now: number) => {
      const t = Math.min(1, (now - start) / duration);
      const p = direction === "in" ? ease(t) : 1 - ease(t);
      Object.assign(el.style, reveal(p));
      if (t < 1) requestAnimationFrame(frame);
      else done();
    };
    requestAnimationFrame(frame);
  });
}

/** Rolls only the characters that changed: `rollDigits(el, "$1,204.50")`. Cells need `.aim-digit` (inline-grid, tabular-nums). */
export function rollDigits(el: HTMLElement, text: string) {
  const timing = waapi("state" as SpringPreset);
  const cells = Array.from(el.children) as HTMLElement[];
  while (cells.length > text.length) cells.pop()!.remove();
  [...text].forEach((ch, i) => {
    let cell = cells[i];
    if (!cell) {
      cell = document.createElement("span");
      cell.className = "aim-digit";
      el.appendChild(cell);
      cells.push(cell);
    }
    const current = cell.lastElementChild as HTMLElement | null;
    if (current?.textContent === ch) return;
    const next = document.createElement("span");
    next.textContent = ch;
    cell.appendChild(next);
    next.animate(transitions.digitIn, timing);
    if (current) current.animate(transitions.digitOut, timing).finished.then(() => current.remove());
  });
  el.setAttribute("aria-label", text);
}

/** Press bounce: grow 15 % on the bounce spring, settle back on release after 180 ms. */
export function pressBounce(el: HTMLElement) {
  el.animate([{ transform: "scale(1)" }, { transform: "scale(1.15)" }], { ...waapi("bounce" as SpringPreset), fill: "forwards" });
  setTimeout(() => el.animate([{ transform: "scale(1.15)" }, { transform: "scale(1)" }], waapi("release" as SpringPreset)), 180);
}

/** Fades only the edge of a scroller that has more content behind it (pair with `.aim-edge-fade` CSS). Returns a cleanup. */
export function edgeFade(scroller: HTMLElement, axis: "x" | "y" = "x") {
  scroller.classList.add("aim-edge-fade");
  if (axis === "y") scroller.classList.add("aim-vertical");
  const update = () => {
    const offset = axis === "x" ? scroller.scrollLeft : scroller.scrollTop;
    const room = axis === "x" ? scroller.scrollWidth - scroller.clientWidth : scroller.scrollHeight - scroller.clientHeight;
    scroller.classList.toggle("fade-start", offset > 1);
    scroller.classList.toggle("fade-end", room - offset > 1);
  };
  update();
  scroller.addEventListener("scroll", update, { passive: true });
  const observer = new ResizeObserver(update);
  observer.observe(scroller);
  return () => {
    scroller.removeEventListener("scroll", update);
    observer.disconnect();
  };
}

/** Layout of one item in an endless wheel picker at signed distance t from the centre. */
export function wheelItem(t: number, pitch: number, kind: "icon" | "pill" = "icon") {
  const d = Math.abs(t);
  const scale = kind === "icon" ? 0.42 + 0.58 * Math.exp(-d) : 0.55 + 0.45 * Math.exp(-1.1 * d);
  const squeeze = d <= 3 ? 1 - 0.1 * d : 0.7;
  return { x: pitch * t * squeeze, scale, opacity: Math.max(0.2, 1 - 0.3 * d), zIndex: Math.round(100 - d * 10) };
}

/**
 * Gesture velocity in px/ms over the last few samples. Use it for momentum
 * dismissal (`Math.abs(v) > 0.11` dismisses a toast/drawer regardless of distance)
 * and for velocity-aware snap points.
 */
export class VelocityTracker {
  private samples: { t: number; v: number }[] = [];
  constructor(private windowMs = 100) {}
  push(value: number, t = performance.now()) {
    this.samples.push({ t, v: value });
    while (this.samples.length > 1 && t - this.samples[0].t > this.windowMs) this.samples.shift();
  }
  velocity(): number {
    if (this.samples.length < 2) return 0;
    const a = this.samples[0], b = this.samples[this.samples.length - 1];
    const dt = Math.max(b.t - a.t, 1);
    return (b.v - a.v) / dt;
  }
  reset() { this.samples = []; }
}

/**
 * Rubber-band damping: past a boundary, the element moves less the further you go.
 * `overshoot` is how far past the edge the pointer went; `limit` caps the visible travel.
 * Returns the damped displacement (same sign as overshoot).
 */
export function damp(overshoot: number, limit = 80, stiffness = 0.55): number {
  const sign = overshoot < 0 ? -1 : 1;
  const x = Math.abs(overshoot);
  return sign * (1 - 1 / ((x * stiffness) / limit + 1)) * limit;
}
